//! Regenerate `tests/vectors.json`, the cross-implementation test vectors for
//! NIP-CM.
//!
//! ```bash
//! cargo run -p buzz-mandate --example mandate-vectors > crates/buzz-mandate/tests/vectors.json
//! ```
//!
//! The Rust suite (`tests/vectors.rs`) and the TypeScript verifier
//! (`desktop/src/shared/mandate/`) both run against this file, so any
//! disagreement between the two implementations fails a test instead of
//! shipping.
//!
//! Keys are derived from the secrets `0x01..0x04` so vectors are reproducible;
//! they are test keys and must never be used for anything else.

use buzz_mandate::{Caveats, MandateChain, RevocationSet, TrustAnchor};
use nostr::Keys;
use serde_json::{json, Value};

fn keys(byte: u8) -> Keys {
    let mut secret = [0u8; 32];
    secret[31] = byte;
    let hex: String = secret.iter().map(|b| format!("{b:02x}")).collect();
    Keys::parse(&hex).expect("valid test secret")
}

fn caveats(s: &str) -> Caveats {
    Caveats::parse(s).unwrap_or_else(|e| panic!("vector caveats {s:?} must parse: {e}"))
}

fn chain_vector(name: &str, description: &str, chain: &MandateChain) -> Value {
    let mandate = chain
        .verify(&TrustAnchor::unchecked(), &RevocationSet::new())
        .expect("vector chains must verify");

    json!({
        "name": name,
        "description": description,
        "envelope": serde_json::from_str::<Value>(&chain.to_json().expect("serialise"))
            .expect("envelope is json"),
        "link_ids": chain.links().iter().map(|l| l.id().to_hex()).collect::<Vec<_>>(),
        "preimages": chain.links().iter().map(buzz_mandate::Link::preimage).collect::<Vec<_>>(),
        "subject": mandate.subject().to_hex(),
        "root_authority": mandate.root_authority().to_hex(),
        "effective_caveats": mandate.effective_caveats().to_canonical_string(),
        "hops": mandate.hops(),
    })
}

fn main() {
    let owner = keys(1);
    let planner = keys(2);
    let worker = keys(3);
    let helper = keys(4);

    let one_hop = MandateChain::root(
        &owner,
        &planner.public_key(),
        caveats("channel=engineering,general&depth=2&expires=1800000000&kind=9,40002"),
    )
    .expect("root");

    let two_hop = one_hop
        .delegate(
            &planner,
            &worker.public_key(),
            caveats("channel=engineering&depth=1&expires=1799990000&kind=9&uses=5"),
        )
        .expect("second hop");

    let three_hop = two_hop
        .delegate(
            &worker,
            &helper.public_key(),
            caveats("channel=engineering&depth=0&expires=1799980000&kind=9&tool=shell&uses=2"),
        )
        .expect("third hop");

    let unconstrained =
        MandateChain::root(&owner, &planner.public_key(), Caveats::default()).expect("root");

    let vectors = json!({
        "protocol": "NIP-CM",
        "version": 1,
        "note": "Generated by `cargo run -p buzz-mandate --example mandate-vectors`. Test keys only.",
        "keys": {
            "owner":   { "secret": "00".repeat(31) + "01", "pubkey": owner.public_key().to_hex() },
            "planner": { "secret": "00".repeat(31) + "02", "pubkey": planner.public_key().to_hex() },
            "worker":  { "secret": "00".repeat(31) + "03", "pubkey": worker.public_key().to_hex() },
            "helper":  { "secret": "00".repeat(31) + "04", "pubkey": helper.public_key().to_hex() },
        },
        "chains": [
            chain_vector("one_hop", "Owner grants the planner two channels and two kinds.", &one_hop),
            chain_vector("two_hop", "Planner narrows to one channel, one kind, a budget, and one remaining hop.", &two_hop),
            chain_vector("three_hop", "Worker narrows again, adding a tool scope and exhausting depth.", &three_hop),
            chain_vector("unconstrained_root", "A root grant with no caveats at all.", &unconstrained),
        ],
        "canonical_caveats": canonical_cases(),
        "invalid_caveats": invalid_cases(),
        "narrowing": narrowing_cases(),
        "authorization": authorization_cases(),
        "invalid_chains": invalid_chain_cases(&two_hop, &one_hop, &planner),
        "actor_binding": actor_binding_cases(&two_hop, &planner, &worker, &helper),
        "trust_anchor": trust_anchor_cases(&one_hop, &owner, &helper),
    });

    println!(
        "{}",
        serde_json::to_string_pretty(&vectors).expect("serialise vectors")
    );
}

/// Strings that MUST parse, each already in canonical form.
fn canonical_cases() -> Value {
    json!([
        "",
        "kind=9",
        "kind=9,40002",
        "channel=engineering&kind=9",
        "channel=engineering,general&depth=2&expires=1800000000&kind=9,40002&not_before=1700000000&tool=shell,str_replace&uses=5",
        "peer=0000000000000000000000000000000000000000000000000000000000000aaa",
        "depth=0",
        "uses=1",
    ])
}

/// Strings that MUST be rejected, with the reason a verifier should report.
fn invalid_cases() -> Value {
    json!([
        { "input": "kind=9&channel=general", "reason": "dimensions out of canonical order" },
        { "input": "kind=9&kind=10", "reason": "duplicate dimension" },
        { "input": "kind=40002,9", "reason": "set members out of numeric order" },
        { "input": "kind=9,9", "reason": "duplicate set member" },
        { "input": "channel=general,engineering", "reason": "set members out of bytewise order" },
        { "input": "&kind=9", "reason": "leading delimiter" },
        { "input": "kind=9&", "reason": "trailing delimiter" },
        { "input": "kind=9&&tool=shell", "reason": "doubled delimiter" },
        { "input": "kind", "reason": "clause missing '='" },
        { "input": "realm=block", "reason": "unknown dimension" },
        { "input": "kind=09", "reason": "leading zero" },
        { "input": "expires=01700000000", "reason": "leading zero" },
        { "input": "kind=65536", "reason": "kind out of range" },
        { "input": "depth=256", "reason": "depth out of range" },
        { "input": "uses=0", "reason": "a zero budget grants nothing" },
        { "input": "kind=", "reason": "empty member set" },
        { "input": "kind=9 ", "reason": "whitespace" },
        { "input": "tool=caf\u{e9}", "reason": "non-ascii" },
        { "input": "tool=sh=ell", "reason": "'=' inside a member" },
        { "input": "peer=deadbeef", "reason": "peer is not a 64-hex pubkey" },
        { "input": "peer=0000000000000000000000000000000000000000000000000000000000000AAA", "reason": "uppercase hex" },
        { "input": "expires=100&not_before=100", "reason": "empty time window" },
        { "input": "expires=100&not_before=200", "reason": "empty time window" }
    ])
}

/// Whether `child` narrows `parent`.
fn narrowing_cases() -> Value {
    json!([
        { "parent": "kind=9,40002", "child": "kind=9", "narrows": true },
        { "parent": "kind=9,40002", "child": "kind=9,40002", "narrows": true },
        { "parent": "kind=9", "child": "kind=9,40002", "narrows": false, "why": "superset widens" },
        { "parent": "channel=engineering", "child": "", "narrows": false, "why": "dropping a constraint is not inheritance" },
        { "parent": "kind=9", "child": "channel=engineering&kind=9", "narrows": true, "why": "adding a dimension narrows" },
        { "parent": "", "child": "channel=engineering&kind=9&uses=1", "narrows": true, "why": "an unconstrained parent admits anything" },
        { "parent": "expires=2000&not_before=1000", "child": "expires=1500&not_before=1200", "narrows": true },
        { "parent": "expires=2000&not_before=1000", "child": "expires=2001&not_before=1000", "narrows": false, "why": "later expiry widens" },
        { "parent": "expires=2000&not_before=1000", "child": "expires=2000&not_before=999", "narrows": false, "why": "earlier start widens" },
        { "parent": "uses=5", "child": "uses=1", "narrows": true },
        { "parent": "uses=5", "child": "uses=6", "narrows": false, "why": "budgets only shrink" },
        { "parent": "depth=2", "child": "depth=1", "narrows": true },
        { "parent": "depth=2", "child": "depth=2", "narrows": false, "why": "depth must strictly decrease" },
        { "parent": "depth=0", "child": "depth=0", "narrows": false, "why": "a parent at zero may not delegate" }
    ])
}

/// Whether a request is authorized, given caveats, a clock, and a use count.
fn authorization_cases() -> Value {
    json!([
        { "caveats": "channel=engineering&kind=9", "now": 1000, "uses_consumed": 0,
          "request": { "kind": 9, "channels": ["engineering"] }, "allowed": true },
        { "caveats": "channel=general&kind=9", "now": 1000, "uses_consumed": 0,
          "request": { "kind": 9, "channels": ["engineering"] }, "allowed": false, "reason": "out_of_scope" },
        { "caveats": "tool=shell", "now": 1000, "uses_consumed": 0,
          "request": { "kind": 9 }, "allowed": false, "reason": "unstated_dimension" },
        { "caveats": "channel=engineering", "now": 1000, "uses_consumed": 0,
          "request": { "channels": ["engineering", "secrets"] }, "allowed": false, "reason": "out_of_scope",
          "why": "every channel an action targets must be permitted, not just the first" },
        { "caveats": "expires=2000&not_before=1000", "now": 999, "uses_consumed": 0,
          "request": {}, "allowed": false, "reason": "not_yet_valid" },
        { "caveats": "expires=2000&not_before=1000", "now": 1000, "uses_consumed": 0,
          "request": {}, "allowed": true, "why": "not_before is inclusive" },
        { "caveats": "expires=2000&not_before=1000", "now": 1999, "uses_consumed": 0,
          "request": {}, "allowed": true },
        { "caveats": "expires=2000&not_before=1000", "now": 2000, "uses_consumed": 0,
          "request": {}, "allowed": false, "reason": "expired", "why": "expires is exclusive" },
        { "caveats": "uses=3", "now": 1000, "uses_consumed": 2, "request": {}, "allowed": true },
        { "caveats": "uses=3", "now": 1000, "uses_consumed": 3, "request": {}, "allowed": false, "reason": "budget_exhausted" },
        { "caveats": "", "now": 0, "uses_consumed": 0, "request": {}, "allowed": true,
          "why": "the unconstrained set permits everything" }
    ])
}

/// Chains a verifier MUST reject, as ready-to-parse envelopes.
///
/// The spec lists these in prose; a second implementation that ran only the
/// caveat vectors could accept every one of them and still look green.
fn invalid_chain_cases(two_hop: &MandateChain, one_hop: &MandateChain, planner: &Keys) -> Value {
    let envelope = |chain: &MandateChain| -> Value {
        serde_json::from_str(&chain.to_json().expect("serialise")).expect("json")
    };
    let mut cases = Vec::new();

    // Caveats edited after signing: the link id changes, the signature does not.
    let mut widened = envelope(two_hop);
    widened["links"][1]["caveats"] =
        json!("channel=engineering,general&depth=1&expires=1799990000&kind=9,40002&uses=5");
    cases.push(json!({
        "name": "widened_after_signing",
        "envelope": widened,
        "reason": "leaf caveats were edited, so the signature no longer matches the link id",
    }));

    // A link from a different chain, pasted in.
    let other_root = MandateChain::root(
        planner,
        &keys(9).public_key(),
        caveats("channel=engineering&depth=1&expires=1799990000&kind=9&uses=5"),
    )
    .expect("other root");
    let mut spliced = envelope(two_hop);
    spliced["links"][1] = envelope(&other_root)["links"][0].clone();
    cases.push(json!({
        "name": "spliced_link",
        "envelope": spliced,
        "reason": "link 1 belongs to another chain: its parent is not link 0's id",
    }));

    // A root link that claims a parent.
    let mut rooted_parent = envelope(two_hop);
    rooted_parent["links"][0]["parent"] = rooted_parent["links"][1]["parent"].clone();
    cases.push(json!({
        "name": "root_with_parent",
        "envelope": rooted_parent,
        "reason": "the root link must have parent: null",
    }));

    // Duplicated leaf: five links, and a repeated subject.
    let mut too_long = envelope(two_hop);
    let leaf = too_long["links"][1].clone();
    if let Some(links) = too_long["links"].as_array_mut() {
        for _ in 0..3 {
            links.push(leaf.clone());
        }
    }
    cases.push(json!({
        "name": "over_max_chain_len",
        "envelope": too_long,
        "reason": "five links exceeds the four-link maximum",
    }));

    // Unknown-field padding: changes the bytes, not the chain.
    let mut padded = envelope(one_hop);
    padded["pad"] = json!("x");
    cases.push(json!({
        "name": "unknown_envelope_field",
        "envelope": padded,
        "reason": "unknown fields are refused so one chain cannot have two encodings",
    }));

    let mut padded_link = envelope(one_hop);
    padded_link["links"][0]["pad"] = json!("x");
    cases.push(json!({
        "name": "unknown_link_field",
        "envelope": padded_link,
        "reason": "unknown link fields are refused for the same reason",
    }));

    let mut bad_version = envelope(one_hop);
    bad_version["v"] = json!(2);
    cases.push(json!({
        "name": "unsupported_version",
        "envelope": bad_version,
        "reason": "envelope version must be 1",
    }));

    Value::Array(cases)
}

/// Authorization cases that state an actor — the rule that defeats truncation.
fn actor_binding_cases(
    two_hop: &MandateChain,
    planner: &Keys,
    worker: &Keys,
    helper: &Keys,
) -> Value {
    let full: Value = serde_json::from_str(&two_hop.to_json().expect("serialise")).expect("json");
    let mut truncated = full.clone();
    if let Some(links) = truncated["links"].as_array_mut() {
        links.truncate(1);
    }

    json!([
        {
            "name": "subject_in_scope",
            "envelope": full.clone(),
            "actor": worker.public_key().to_hex(),
            "now": 1_799_000_000u64,
            "request": { "kind": 9, "channels": ["engineering"] },
            "allowed": true,
        },
        {
            "name": "truncated_prefix_names_another_subject",
            "envelope": truncated.clone(),
            "actor": worker.public_key().to_hex(),
            "now": 1_799_000_000u64,
            "request": { "kind": 9, "channels": ["general"] },
            "allowed": false,
            "reason": "wrong_subject",
            "why": "the prefix grants #general, but to the planner — not to the worker",
        },
        {
            "name": "truncated_prefix_is_valid_for_its_own_subject",
            "envelope": truncated,
            "actor": planner.public_key().to_hex(),
            "now": 1_799_000_000u64,
            "request": { "kind": 9, "channels": ["general"] },
            "allowed": true,
        },
        {
            "name": "a_third_party_holds_nothing",
            "envelope": full.clone(),
            "actor": helper.public_key().to_hex(),
            "now": 1_799_000_000u64,
            "request": { "kind": 9, "channels": ["engineering"] },
            "allowed": false,
            "reason": "wrong_subject",
        },
        {
            "name": "every_targeted_channel_must_be_in_scope",
            "envelope": full,
            "actor": worker.public_key().to_hex(),
            "now": 1_799_000_000u64,
            "request": { "kind": 9, "channels": ["engineering", "secrets"] },
            "allowed": false,
            "reason": "out_of_scope",
            "why": "an event may carry many h tags; checking only the first authorizes the rest",
        }
    ])
}

/// A chain is only worth what its root is worth.
fn trust_anchor_cases(one_hop: &MandateChain, owner: &Keys, impostor: &Keys) -> Value {
    let self_issued =
        MandateChain::root(impostor, &keys(3).public_key(), Caveats::default()).expect("root");
    let self_issued_json: Value =
        serde_json::from_str(&self_issued.to_json().expect("serialise")).expect("json");

    json!([
        {
            "name": "trusted_root",
            "envelope": serde_json::from_str::<Value>(&one_hop.to_json().expect("serialise"))
                .expect("json"),
            "trusted_roots": [owner.public_key().to_hex()],
            "valid": true,
        },
        {
            "name": "self_issued_unconstrained_chain",
            "envelope": self_issued_json.clone(),
            "trusted_roots": [owner.public_key().to_hex()],
            "valid": false,
            "reason": "untrusted_root",
            "why": "internally flawless and grants everything; only the anchor stops it",
        },
        {
            "name": "self_issued_chain_is_internally_consistent",
            "envelope": self_issued_json,
            "trusted_roots": Value::Null,
            "valid": true,
            "why": "with no anchor, structure alone is all that is checked — which is the trap",
        }
    ])
}
