//! Regenerate `tests/vectors.json`, the cross-implementation test vectors for
//! NIP-CM.
//!
//! ```bash
//! cargo run -p buzz-mandate --example mandate-vectors > crates/buzz-mandate/tests/vectors.json
//! ```
//!
//! The Rust suite (`tests/vectors.rs`) and the TypeScript verifier
//! (`desktop/src/shared/mandate/`) both run against this file, so any
//! disagreement between the two implementations fails a test instead of
//! shipping.
//!
//! Keys are derived from the secrets `0x01..0x04` so vectors are reproducible;
//! they are test keys and must never be used for anything else.

use buzz_mandate::{Caveats, MandateChain};
use nostr::Keys;
use serde_json::{json, Value};

fn keys(byte: u8) -> Keys {
    let mut secret = [0u8; 32];
    secret[31] = byte;
    let hex: String = secret.iter().map(|b| format!("{b:02x}")).collect();
    Keys::parse(&hex).expect("valid test secret")
}

fn caveats(s: &str) -> Caveats {
    Caveats::parse(s).unwrap_or_else(|e| panic!("vector caveats {s:?} must parse: {e}"))
}

fn chain_vector(name: &str, description: &str, chain: &MandateChain) -> Value {
    let mandate = chain
        .verify(&buzz_mandate::RevocationSet::new())
        .expect("vector chains must verify");

    json!({
        "name": name,
        "description": description,
        "envelope": serde_json::from_str::<Value>(&chain.to_json().expect("serialise"))
            .expect("envelope is json"),
        "link_ids": chain.links().iter().map(|l| l.id().to_hex()).collect::<Vec<_>>(),
        "preimages": chain.links().iter().map(buzz_mandate::Link::preimage).collect::<Vec<_>>(),
        "subject": mandate.subject().to_hex(),
        "root_authority": mandate.root_authority().to_hex(),
        "effective_caveats": mandate.effective_caveats().to_canonical_string(),
        "hops": mandate.hops(),
    })
}

fn main() {
    let owner = keys(1);
    let planner = keys(2);
    let worker = keys(3);
    let helper = keys(4);

    let one_hop = MandateChain::root(
        &owner,
        &planner.public_key(),
        caveats("channel=engineering,general&depth=2&expires=1800000000&kind=9,40002"),
    )
    .expect("root");

    let two_hop = one_hop
        .delegate(
            &planner,
            &worker.public_key(),
            caveats("channel=engineering&depth=1&expires=1799990000&kind=9&uses=5"),
        )
        .expect("second hop");

    let three_hop = two_hop
        .delegate(
            &worker,
            &helper.public_key(),
            caveats("channel=engineering&depth=0&expires=1799980000&kind=9&tool=shell&uses=2"),
        )
        .expect("third hop");

    let unconstrained =
        MandateChain::root(&owner, &planner.public_key(), Caveats::default()).expect("root");

    let vectors = json!({
        "protocol": "NIP-CM",
        "version": 1,
        "note": "Generated by `cargo run -p buzz-mandate --example mandate-vectors`. Test keys only.",
        "keys": {
            "owner":   { "secret": "00".repeat(31) + "01", "pubkey": owner.public_key().to_hex() },
            "planner": { "secret": "00".repeat(31) + "02", "pubkey": planner.public_key().to_hex() },
            "worker":  { "secret": "00".repeat(31) + "03", "pubkey": worker.public_key().to_hex() },
            "helper":  { "secret": "00".repeat(31) + "04", "pubkey": helper.public_key().to_hex() },
        },
        "chains": [
            chain_vector("one_hop", "Owner grants the planner two channels and two kinds.", &one_hop),
            chain_vector("two_hop", "Planner narrows to one channel, one kind, a budget, and one remaining hop.", &two_hop),
            chain_vector("three_hop", "Worker narrows again, adding a tool scope and exhausting depth.", &three_hop),
            chain_vector("unconstrained_root", "A root grant with no caveats at all.", &unconstrained),
        ],
        "canonical_caveats": canonical_cases(),
        "invalid_caveats": invalid_cases(),
        "narrowing": narrowing_cases(),
        "authorization": authorization_cases(),
    });

    println!(
        "{}",
        serde_json::to_string_pretty(&vectors).expect("serialise vectors")
    );
}

/// Strings that MUST parse, each already in canonical form.
fn canonical_cases() -> Value {
    json!([
        "",
        "kind=9",
        "kind=9,40002",
        "channel=engineering&kind=9",
        "channel=engineering,general&depth=2&expires=1800000000&kind=9,40002&not_before=1700000000&tool=shell,str_replace&uses=5",
        "peer=0000000000000000000000000000000000000000000000000000000000000aaa",
        "depth=0",
        "uses=1",
    ])
}

/// Strings that MUST be rejected, with the reason a verifier should report.
fn invalid_cases() -> Value {
    json!([
        { "input": "kind=9&channel=general", "reason": "dimensions out of canonical order" },
        { "input": "kind=9&kind=10", "reason": "duplicate dimension" },
        { "input": "kind=40002,9", "reason": "set members out of numeric order" },
        { "input": "kind=9,9", "reason": "duplicate set member" },
        { "input": "channel=general,engineering", "reason": "set members out of bytewise order" },
        { "input": "&kind=9", "reason": "leading delimiter" },
        { "input": "kind=9&", "reason": "trailing delimiter" },
        { "input": "kind=9&&tool=shell", "reason": "doubled delimiter" },
        { "input": "kind", "reason": "clause missing '='" },
        { "input": "realm=block", "reason": "unknown dimension" },
        { "input": "kind=09", "reason": "leading zero" },
        { "input": "expires=01700000000", "reason": "leading zero" },
        { "input": "kind=65536", "reason": "kind out of range" },
        { "input": "depth=256", "reason": "depth out of range" },
        { "input": "uses=0", "reason": "a zero budget grants nothing" },
        { "input": "kind=", "reason": "empty member set" },
        { "input": "kind=9 ", "reason": "whitespace" },
        { "input": "tool=caf\u{e9}", "reason": "non-ascii" },
        { "input": "tool=sh=ell", "reason": "'=' inside a member" },
        { "input": "peer=deadbeef", "reason": "peer is not a 64-hex pubkey" },
        { "input": "peer=0000000000000000000000000000000000000000000000000000000000000AAA", "reason": "uppercase hex" },
        { "input": "expires=100&not_before=100", "reason": "empty time window" },
        { "input": "expires=100&not_before=200", "reason": "empty time window" }
    ])
}

/// Whether `child` narrows `parent`.
fn narrowing_cases() -> Value {
    json!([
        { "parent": "kind=9,40002", "child": "kind=9", "narrows": true },
        { "parent": "kind=9,40002", "child": "kind=9,40002", "narrows": true },
        { "parent": "kind=9", "child": "kind=9,40002", "narrows": false, "why": "superset widens" },
        { "parent": "channel=engineering", "child": "", "narrows": false, "why": "dropping a constraint is not inheritance" },
        { "parent": "kind=9", "child": "channel=engineering&kind=9", "narrows": true, "why": "adding a dimension narrows" },
        { "parent": "", "child": "channel=engineering&kind=9&uses=1", "narrows": true, "why": "an unconstrained parent admits anything" },
        { "parent": "expires=2000&not_before=1000", "child": "expires=1500&not_before=1200", "narrows": true },
        { "parent": "expires=2000&not_before=1000", "child": "expires=2001&not_before=1000", "narrows": false, "why": "later expiry widens" },
        { "parent": "expires=2000&not_before=1000", "child": "expires=2000&not_before=999", "narrows": false, "why": "earlier start widens" },
        { "parent": "uses=5", "child": "uses=1", "narrows": true },
        { "parent": "uses=5", "child": "uses=6", "narrows": false, "why": "budgets only shrink" },
        { "parent": "depth=2", "child": "depth=1", "narrows": true },
        { "parent": "depth=2", "child": "depth=2", "narrows": false, "why": "depth must strictly decrease" },
        { "parent": "depth=0", "child": "depth=0", "narrows": false, "why": "a parent at zero may not delegate" }
    ])
}

/// Whether a request is authorized, given caveats, a clock, and a use count.
fn authorization_cases() -> Value {
    json!([
        { "caveats": "channel=engineering&kind=9", "now": 1000, "uses_consumed": 0,
          "request": { "kind": 9, "channel": "engineering" }, "allowed": true },
        { "caveats": "channel=general&kind=9", "now": 1000, "uses_consumed": 0,
          "request": { "kind": 9, "channel": "engineering" }, "allowed": false, "reason": "out_of_scope" },
        { "caveats": "tool=shell", "now": 1000, "uses_consumed": 0,
          "request": { "kind": 9 }, "allowed": false, "reason": "unstated_dimension" },
        { "caveats": "expires=2000&not_before=1000", "now": 999, "uses_consumed": 0,
          "request": {}, "allowed": false, "reason": "not_yet_valid" },
        { "caveats": "expires=2000&not_before=1000", "now": 1000, "uses_consumed": 0,
          "request": {}, "allowed": true, "why": "not_before is inclusive" },
        { "caveats": "expires=2000&not_before=1000", "now": 1999, "uses_consumed": 0,
          "request": {}, "allowed": true },
        { "caveats": "expires=2000&not_before=1000", "now": 2000, "uses_consumed": 0,
          "request": {}, "allowed": false, "reason": "expired", "why": "expires is exclusive" },
        { "caveats": "uses=3", "now": 1000, "uses_consumed": 2, "request": {}, "allowed": true },
        { "caveats": "uses=3", "now": 1000, "uses_consumed": 3, "request": {}, "allowed": false, "reason": "budget_exhausted" },
        { "caveats": "", "now": 0, "uses_consumed": 0, "request": {}, "allowed": true,
          "why": "the unconstrained set permits everything" }
    ])
}
